apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./service.yaml

configMapGenerator:
  - name: backend-config
    envs: 
      - env/.env.config

secretGenerator:
  - name: backend-secrets
    envs: 
      - env/.env.secret