apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./service.yaml

configMapGenerator:
  - name: frontend-html
    files: # using files here as we want to create a whole file
      - html/index.html