apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - percona.yaml
  - roles.yaml
  - job.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: db-init-scripts
    files: # using files here as we want to create a whole file
      - sql/schema-quotes-init.sql
  - name: patch-script
    files:
      - scripts/update-secret.sh
secretGenerator:
  - name: postgres-update-secrets
    envs:
      - env/.env.postgres