apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: argo-cd
spec:
  forProvider:
    chart:
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version: 5.42.1
    namespace: argocd
  providerConfigRef:
    name: default
