kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kube-lab-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
    extraMounts:
      - hostPath: ./cluster-data
        containerPath: /var/local-path-provisioner